//Localhost
### Get all pokemon
GET http://localhost:3000/pokemon

### Get one pokemon
GET http://localhost:3000/pokemon/67e6a1d4496a77491ab327

### Create one pokemon
POST http://localhost:3000/pokemon HTTP/1.1
content-type: application/json

{
  "pokedexNo": 0,
  "name": "MissingNo",
  "nickname": "Cartridge",
  "level": 0,
  "nature": "???",
  "heldItem": "",
  "originalTrainer": "???"
}

### Update one pokemon
PUT http://localhost:3000/pokemon/67e6a1d4496a77491ab327e9 HTTP/1.1
content-type: application/json

{
  "pokedexNo": 0,
  "name": "MissingNo",
  "nickname": "Cartridge",
  "level": 0,
  "nature": "???",
  "heldItem": "",
  "originalTrainer": "???"
}

### Delete one pokemon
DELETE http://localhost:3000/pokemon/67e6a3321cf157f4d3b1b281 HTTP/1.1