//Localhost
//For pokemon
### Get all pokemon
GET http://localhost:3000/pokemon

### Get one pokemon
GET http://localhost:3000/pokemon/67ecc3520b9b2bdcc0ff7191

### Create one pokemon
POST http://localhost:3000/pokemon HTTP/1.1
content-type: application/json

{
  "pokedexNo": 0,
  "name": "MissingNo",
  "nickname": "Cartridge",
  "level": "asd",
  "nature": "???",
  "heldItem": "",
  "originalTrainer": "???"
}

### Update one pokemon
PUT http://localhost:3000/pokemon/67ecc3520b9b2bdcc0ff7191 HTTP/1.1
content-type: application/json

{
  "pokedexNo": 0,
  "name": "MissingNo",
  "nickname": "Cartridge",
  "level": 0,
  "nature": "???",
  "heldItem": "",
  "originalTrainer": "???"
}

### Delete one pokemon
DELETE http://localhost:3000/pokemon/67ecc3520b9b2bdcc0ff7191 HTTP/1.1

//For Persona
### Get all persona
GET http://localhost:3000/persona

### Get one persona
GET http://localhost:3000/persona/67ecb3999ccea7b798073ea7

### Create one persona
POST http://localhost:3000/persona HTTP/1.1
content-type: application/json

{
  "persona": "Kagura",
  "arcana": "Priestess",
  "level": "15",
  "awakenInto": "N/A",
  "firstAppearance": "Mobile Legends",
  "user": "Lemon",
  "denote": "Original"

}

### Update one persona
PUT http://localhost:3000/persona/67ecb3999ccea7b798073ea7 HTTP/1.1
content-type: application/json

{
  "persona": "Hanabi",
  "arcana": "Star",
  "level": 15,
  "awakenInto": "N/A",
  "firstAppearance": "Mobile Legends",
  "user": "Jenkin",
  "denote": "Original"
}

### Delete one persona
DELETE http://localhost:3000/persona/67ecbfb0a3c75dc511127766 HTTP/1.1
